name: flutter_oss_licenses
description: A tool for generating detail and better OSS license list using pubspec.lock.
homepage: https://github.com/espresso3389/flutter_oss_licenses
version: "0.6.4"

environment:
  sdk: ">=2.0.0 <3.0.0"

executables:
  generate:

dependencies:
  path: ^1.4.0
  meta: ^1.1.0
  yaml: ^2.1.0

dev_dependencies:
